import type { Metadata } from "next";
import { Jersey_10, Jaro } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import ControlsProvider from "@/context/ControlsProvider";

const jersey10 = Jersey_10({
  variable: "--font-jersey",
  subsets: ["latin"],
  weight: "400",
});

const jaro = Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jaro.variable} ${jersey10.variable} antialiased`}>
        <div className="h-screen">
          <div className="bg-radial from-primary from-20% to-primary-dark h-full to-100% flex gap-6 flex-col px-5">
            <ControlsProvider>
              <Layout>{children}</Layout>
            </ControlsProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
